version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: minh
      MYSQL_PASSWORD: minh
    ports:
      - 3308:3306
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
